USE [master]
GO

/****** Object:  Database [Auta]    Script Date: 02.10.2020 16:22:41 ******/
DROP DATABASE [Auta]
GO

/****** Object:  Database [Auta]    Script Date: 02.10.2020 16:22:41 ******/
CREATE DATABASE [Auta]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Auta', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Auta.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Auta_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Auta_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Auta].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Auta] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Auta] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Auta] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Auta] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Auta] SET ARITHABORT OFF 
GO

ALTER DATABASE [Auta] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Auta] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Auta] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Auta] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Auta] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Auta] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Auta] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Auta] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Auta] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Auta] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Auta] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Auta] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Auta] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Auta] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Auta] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Auta] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Auta] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Auta] SET RECOVERY FULL 
GO

ALTER DATABASE [Auta] SET  MULTI_USER 
GO

ALTER DATABASE [Auta] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Auta] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Auta] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Auta] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Auta] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Auta] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Auta] SET  READ_WRITE 
GO

