//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auta
    {
        public int Id { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Numer { get; set; }
        public Nullable<System.DateTime> Ubezpieczenie { get; set; }
        public Nullable<System.DateTime> OC { get; set; }
    }
}
